spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/ORCL
    username: STUDY
    password: 123qweQWE
    hikari: # https://github.com/brettwooldridge/HikariCP (uses milliseconds for all time values)
      maximumPoolSize: 10
      minimumIdle: 2
      idleTimeout: 600000
      connectionTimeout: 30000
      maxLifetime: 1800000

