spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/study?serverTimezone=Etc/GMT-8&rewriteBatchedStatements=true
    username: root
    password: 123456
    hikari: # https://github.com/brettwooldridge/HikariCP (uses milliseconds for all time values)
      maximumPoolSize: 10
      minimumIdle: 2
      idleTimeout: 600000
      connectionTimeout: 30000
      maxLifetime: 1800000

