



#??actuator?????endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

#??log??
logging:
  file:
    path: ./log
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS